apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dora-test-workloads
  namespace: argocd
  annotations:
    # Wave 1: workloads deploy AFTER policies are active
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: file:///home/mohit/dora-as-code
    targetRevision: HEAD
    path: manifests
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dora-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
